services:
  web:
    image: nginx:alpine
    container_name: fits-video
    ports:
      - "8888:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
