services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitsvideo-dev-front
    container_name: fitsvideo-dev-front
    ports:
      - "8002:80"
    restart: unless-stopped
